name: Docker Image CI

on:
  schedule:
    - cron: "37 0 * * 1"
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: HorayNarea
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t ghcr.io/horaynarea/diffoscope:latest .

      - name: Push image
        run: docker push ghcr.io/horaynarea/diffoscope:latest
