name: Docker Image CI

on:
  schedule:
    - cron: "37 0 * * 1"
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t horaynarea/diffoscope:latest .
